sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t jorgejsilva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jorgejsilva/docker-react npm run test